### ISSUE TITLE
Chantiers en cours

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#102]
Ou en sommes nous:

Pour les bugs/regressions trouvé du à ce chantier c'est ici -> https://github.com/mart1ver/oressource/issues/109 !

- [x] Reprendre les interfaces des bilans/sortie/~collectes~ pour les rendre plus interactives (ne pas afficher les catégories sans saisies)
- - [x] collectes (en test)
- Sorties voir  et https://github.com/mart1ver/oressource/pull/101
- - [x] sorties don (en test sur dev) 👍
- - [x] sorties recycleur https://github.com/mart1ver/oressource/pull/114
- - [x] sorties partenaires
- - [x] sorties déchetterie (dans la prochaine PR)
- - [x] sorties poubelles #(dans la prochaine PR)
- [ ] Permettre l'annulation dans les saisies du client sur les collectes et les sorties via JavaScript
- - [x] Saisie par item (en test sur dev)
- - [ ] Annulation (Repoussé pour le prochain passage dev->master mais pas trop dur a faire)
- [ ] Nettoyer les sources au passage (en cours mais déjà beaucoup de lignes ont sauté 🎉 )
- [ ] Reformuler les bilans (ventes, collectes, sorties, dans l'ordre de priorité...) (repoussé mais voir #111 c'est un début)
- [ ] Finir de mettre en place les fonctionnalités autour de la pesée caisse (faut qu'on se prene un moment pour en parler :))

Si tu vois des trucs que j'aurais oublier de noter hésite pas.

**Comment by darnuria** [comment]
PS: Je ne peux pas éditer le wiki.

**Comment by mart1ver** [comment]
yes, 
je t'ai invité au wiki,
dans les 'priorités' on a aussi:
* [ ] reformuler les bilans (ventes, collectes, sorties, dans l'ordre de priorité...) 
* [ ] finir de metre en place les fonctionnalités autour de la pesée caisse

**Comment by darnuria** [comment]
Je me remet dessus ce weekend

**Comment by darnuria** [comment]
Pour l'annulation de masses pesées c'est dans le code juste pas encore accessible depuis l'UI voir #106

**Comment by darnuria** [comment]
J'ai commencer à réécrire les sorties sur cette branche https://github.com/darnuria/oressource/tree/refonte/sorties .

Aussi j'ai documenter tout `js/ticket.js` me reste à gérer les sorties(sorties.php) cote serveur.

**Comment by darnuria** [comment]
Piste pour authentifier les échanges: https://www.ida.liu.se/~TDP024/labs/hmacarticle.pdf
Piste pour Chiffrer les échanges au moins le login: HTTPS...?

**Comment by darnuria** [comment]
EDIT: édit du post original.

**Comment by darnuria** [comment]
@mart1ver Je fini le travail sur les sorties d'ici demain soir.  Ensuite faudra faire la chasse aux petits bugs et modifications imprévues d'UI. Les modifications que j'ai faites simplifient vraiment la gestion d'une sortie cote client. :)

Cote UI je suis vraiment pour qu'on essaie de pas trop faire de différences entre les différentes sorties en attendant d'introduire un moteur de template juste histoire de avoir a maintenir 5 UI différente...

**Comment by darnuria** [comment]
@mart1ver Tiens si tu veux aller voir ça avance bien fait bien attention aux sorties déchetteries j'ai essayer des changement d'interface en allant voir la doc de bootstrap. 
https://github.com/darnuria/oressource/tree/refonte/sorties_last
C'est presque prêt pour faire une pull-request. :)

**Comment by darnuria** [comment]
https://github.com/mart1ver/oressource/issues/144
Je met tout ça dans le wiki pour garder un historique des idées sorties et je ferme vu que des issues spécifiques ont été faites.
