### ISSUE TITLE
Bilan sortie détaillé pour les partenaires

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#122]

**Comment by darnuria** [comment]
Je propose qu'on repousse ça pour la prochaine version «sérieuse» genre disons une 0.3.x en considérant que si on fait des 0.2.x ça sera idéalement que des correctifs de la version 0.2.0.

Car à première vu c'est bien plus que 10h de boulot pour faire un truc assez joli et qui fonctionne bien vu l'état de la page initial.
