### ISSUE TITLE
Le soustracteur de masse des conteneurs ne s'affiche pas aux collectes

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#135]
Ligne du bug:
https://github.com/mart1ver/oressource/blob/dev/ifaces/collecte.php#L117

C'est une typo sur la fonction à appeler voir ici pour le bon nom:
https://github.com/mart1ver/oressource/blob/dev/core/requetes.php#L77

Un fix serait de remplacer la ligne ligne 117 de `ifaces/collectes.php`:
```php
<?php foreach (types_conteneurs($bdd) as $conteneur) { ?>
```
par
```php
<?php foreach (types_contenants($bdd) as $conteneur) { ?>
```

**Comment by mart1ver** [comment]
fait!!
Ça marche, il subsiste un petit accro de mise en page par rapport à l’irréprochable  nouvelle mise en page des sorties hors boutique

**Comment by darnuria** [comment]
Ah? Essaie de poster une capture d'écran je vois pas à première vue.

**Comment by darnuria** [comment]
J'ai ouvert un bug dédié pour le soucis de CSS. #143
