### ISSUE TITLE
Les commentaires et les sondages ne s’effacent pas dans les collectes et les sorties

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#139]

**Comment by darnuria** [comment]
Ok pour les commentaires qu'appelle tu un sondage? Je passerais un œil dans le code demain soir normalement

**Comment by darnuria** [comment]
Résolution du soucis sur les commentaires dans: https://github.com/mart1ver/oressource/pull/141

**Comment by darnuria** [comment]
J'ai ouvert un bug dédié pour le soucis de CSS. https://github.com/mart1ver/oressource/issues/143

**Comment by darnuria** [comment]
Je vérifie si ça fonctionne dans les collectes.
