### ISSUE TITLE
Le graphique du nombre de pièces vendues réagit mal sur l'index

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#140]
faute aux "pesées pour statistiques" requette sql derrière ce graphique à revoir, les pieces vendues doivent posséder une vente et un encaissement

**Comment by darnuria** [comment]
Dans le bilan des ventes?

**Comment by darnuria** [comment]
Ah je vois ou je suis tombe sur le soucis.

**Comment by darnuria** [comment]
Bon vu qu'on va virer les pesees stat pour la prochaine version et les refaire entierement c'est presque 'corrigé' en somme?
