### ISSUE TITLE
Problème de CSS sur les collectes

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#143]
Citation issue de https://github.com/mart1ver/oressource/issues/135
> Ça marche, il subsiste un petit accro de mise en page par rapport à l’irréprochable nouvelle mise en 
> page des sorties hors boutique

Tu peux me sortir une capture d'écran j'arrive vraiment pas à voir ça.

**Comment by mart1ver** [comment]
souci réglé avec la calculette sous forme de widget...
