### ISSUE TITLE
Repertorier et corriger les pages cassées

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#149]
- grilles_prix fix https://github.com/mart1ver/oressource/pull/148
- destroy.php ?
- utilisateurs.php
- edition_types* excepté ventes (je crois)
- pesee_stat (OK faut revoir façon toute la gestion des pesee_vendu)

**Comment by darnuria** [comment]
types_contenants ![type_contenant](https://cloud.githubusercontent.com/assets/2827553/24127183/15ddae26-0dd3-11e7-9c4e-7ea2d1d1f624.png)

**Comment by darnuria** [comment]
types poubelles ![types_poubelles](https://cloud.githubusercontent.com/assets/2827553/24127306/cdbd17de-0dd3-11e7-84a5-abee155f5bc5.png)

**Comment by darnuria** [comment]
utilisateurs 
![utilisateurs](https://cloud.githubusercontent.com/assets/2827553/24127312/dc93d856-0dd3-11e7-88b5-05c06a27f25d.png)

**Comment by mart1ver** [comment]
mon serveur n'est pas aussi verbeux que le tien , je ne profite donc pas de ces messages d’erreur , en tout cas, ces champs peuvent recevoir des données à partir du POST ou du GET (ou des deux), le cas simple ou il n'y a mi POST ni GET est mal pris en charge....

**Comment by darnuria** [comment]
On 21/03/2017 15:22, Vert martin wrote:
> mon serveur n'est pas aussi verbeux que le tien , je ne profite donc pas de ces messages d’erreur , en tout cas, ces champs peuvent recevoir des données à partir du POST ou du GET (ou des deux), le cas simple ou il n'y a mi POST ni GET est mal pris en charge....

(Pour avoir les logs regarde dans `/var/log/apache2/` avec les réglages par
défauts ça parle la dedans. Le fichier fini en `.error` je crois.)

L'idée de passer des paramétrés par GET me plaît bien mais pour cela c'est plus
courant de faire ça avec l'API plutôt que une page utilisable par un humain.

Quand on écrira l'API on pourras réintroduire cette fonctionnalité. :)

En parlant de cette API on pourras faire ça une fois le ménage préliminaire
fini. C'est pour dans pas si longtemps si on regarde bien en fait. ;)
