### ISSUE TITLE
Mettre des placeholder pour les <select> des sondages aux collectes et au sorties

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#152]
On souhaite réintroduire des placeholder sur les `<select>` des pages de collectes et de sorties.

**Comment by darnuria** [comment]
Une solution élégante serais de faire comme une des trois premières réponses. Ça nécessaire aucun support en JS hors mi sur les recycleurs je pense.
https://stackoverflow.com/questions/5805059/how-do-i-make-a-placeholder-for-a-select-box

**Comment by darnuria** [comment]
Cependant j'aimerais bien avoir le retour de personnes de la rockette quand à l'absence de placeholder en proposant le choix le plus fréquemment utilisé par défaut. Pour évalué en terme d'ergonomie pour un utilisateur confirmé.

**Comment by darnuria** [comment]
Reste encore quelques onglets de sorties qui ne proposent pas cette fonctionnalité. On va faire un commit avec @mart1ver cet après-midi pour clore ça.

**Comment by darnuria** [comment]
C'est géré par #205 et #206.
