### ISSUE TITLE
Interopérabilité avec AGATAS

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#153]
Lien vers l'issue d'interopérabilité avec Oressource: https://framagit.org/AGATAs/social-viz/issues

**Comment by darnuria** [comment]
C'est en lien avec https://github.com/mart1ver/oressource/issues/129 et la réalisation d'une API interne/externe pour oressource

**Comment by GammaNu** [comment]
J'ai rangé ça chez nous, c'est désormais ici qu'est issue correspondante : https://framagit.org/mycelia/mycelia-server-nodejs/issues/5

On devrais avoir d'ici moins d'un mois une api auprès de la quelle on peut s'authentifier puis envoyer des données. Dans un premier temps elle ne gèrera que notre format. Ensuite on verra si on étend ses fonctionnalités en interne ou si on fait un module à part, voir un "middleware" qui discute avec Oressource d'un coté, converti et discute avec Mycelia de l'autre coté. C'est la façon de faire qui me semble la plus propre/modulaire pour ne pas faire augmenter la complexité de chaque programme innutilement.

**Comment by darnuria** [comment]
@GammaNu gros temps de réponse mais on réponds. Comme tu as du le sentir on à une petite dette technique à résoudre. On est trois à fourmiller dedans raisonnablement.

On à en plus des utilisateurs donc on essaye de sortir une version mi-août débarrassé des gros bugs et bien nettoyé.

Voila notre feuille de route d'ici la on aura sûrement une API privée pour dialoguer entre notre client web et le serveur d'ici soyons large 3 mois.

Du coup pour se connecter avec vous ou vous qui vous vous connectez à nous c'est pas perdu mais c'est pas pour demain non plus.

@mart1ver: Edit moi si j'ai mal retranscrit ce qu'on s'était dit en réunion avec @yvan-sraka.
