### ISSUE TITLE
Passer par defaut la base SQL de Oressource en UTF-8

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#155]
Actuellement la base de test est en latin1 et les bases installées aussi.
Pour les nouvelles installations ça sera facile.
Pour les anciennes faut faire un script de mise à jour SQL.

**Comment by darnuria** [comment]
piste à suivre: http://www.alphadevx.com/a/420-Converting-a-MySQL-database-from-latin1-to-utf8

**Comment by darnuria** [comment]
@mart1ver Urgent: à voir dimanche ensemble apparemment mariadb est par défaut en  UTF-8.

**Comment by mart1ver** [comment]
@darnuria faire un script shell pour automatiser.
Procédure suivie pour la rck:
Suite à un passage à MariaDB  on à eu des soucis de passage en utf8 prématuré.
Du coup on repasse en `latin1` on dump la base puis on applique un programme de conversion utf8 to latin1 puis on repasse tout en utf8 pour résoudre les soucis:

`ALTER DATABASE oressource CHARACTER SET latin1 COLLATE latin1_swedish_ci;`
puis changer toute les tables:
```bash
sed -e 's/CHARSET\=latin1/CHARSET\=utf8\ COLLATE\=utf8_general_ci/g' \
| iconv -f latin1 -t utf8 \
| mysql -u root --password='password'
```

Puis repasser la base en utf8:
`ALTER DATABASE oressource CHARACTER SET utf8 COLLATE utf8_general_ci;`




Petit script de correction de données déjà corrigées par un humain à la main:
```bash
#!/bin/bash

echo "Script de conversion d'une base de latin1 vers utf8 partiellement déjà convertie par un humain";
echo "N'agit que sur 'à', 'é', 'è', 'ê' et '€'.";

echo $#;

if [ "$#" -eq 1 ] ; then
    sed -e 's/Ã /à/g' < $1 | sed -e 's/Ã©/é/g' | sed -e 's/Ã¨/è/g' | sed -e 's/â‚¬/€/g' | sed -e 's/Ãª/ê/g' > "$1_correct";
else
  echo "Passez le dump sql en paramètre."
fi

exit 0;
```

**Comment by darnuria** [comment]
Voir aussi https://github.com/darnuria/oressource/tree/utf8

**Comment by darnuria** [comment]
Attention on a fait des conneries. Le bon encoding c'est utf8mb4 x(
https://stackoverflow.com/questions/202205/how-to-make-mysql-handle-utf-8-properly

**Comment by darnuria** [comment]
C'est un bug propre à la rockette je vais le séparer de la milestone ayant ajouté un moyen de choisir son charset dans #378.
