### ISSUE TITLE
Revert/correct 784bd3d392d270cb5c88e5f10427acc7094b4c91

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#156]
@mart1ver  On a quelques soucis sur `dev` avec https://github.com/mart1ver/oressource/commit/784bd3d392d270cb5c88e5f10427acc7094b4c91

Tu peux la revert ou corriger? Fait comme tu le sens si tu fait un patch c'est pas dramatique le soucis c'est les lignes avec les `++`.

**Comment by darnuria** [comment]
Partiellement résolu par #159 et #161

**Comment by mart1ver** [comment]
je m'y colle des que possible , sorry je serait passé par une pull request tu m'aurai relu ça ne serait pas arrivé, 100% de ma faute

**Comment by darnuria** [comment]
On 27/03/2017 11:44, Vert martin wrote:
> je m'y colle des que possible , sorry je serait passé par une pull request tu m'aurai relu ça ne serait pas arrivé, 100% de ma faute

Pas de soucis, on fait tous des erreurs. ;)

Reste aide.php je crois qui est touché.

**Comment by mart1ver** [comment]
ayé ! bug réparé!
