### ISSUE TITLE
Nettoyage + indentation de tout les fichiers.

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#162]
Au moins pour la forme corriger l’indentation avec Netbeans, 
virer les commentaires faux ou inutiles et ajouter l’entête de la licence AGPL
sur tout les fichiers php.

Et les trucs vraiment étranges (multiples Inclusions) de `dbconfig.php`.

**Comment by darnuria** [comment]
voir #173

**Comment by darnuria** [comment]
Virer le code mort ou pas exécute est aussi une bonne idée quitte à mettre dans des branches à part les expérimentations! :)

**Comment by darnuria** [comment]
C'est quasiment fini entre #202 et #203 on aura bouclé la partie ré-indentation au minimum.

**Comment by yvan-sraka** [comment]
cf. https://github.com/mart1ver/oressource/pull/198 & https://github.com/mart1ver/oressource/pull/201

**Comment by darnuria** [comment]
cf. #209 et #208

**Comment by darnuria** [comment]
Une fois https://github.com/mart1ver/oressource/pull/212 on en parle plus.

**Comment by darnuria** [comment]
OH yeah!
