### ISSUE TITLE
Le timepicker n'est pas fonctionnel au bilan des ventes

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#164]
à investiguer , je pond une PR tout de suite

**Comment by mart1ver** [comment]
il n'est pas fonctionnel uniquement à partir du moment ou la période visée ne contient pas de données

**Comment by darnuria** [comment]
Donc si je résume bien. Quand on sélectionne un intervalle sans données il y aurais un soucis avec le datepicker? Dans les fait c'est décorrélé vu que le datepicker prépare juste date1 et date2 dans URL dans le code la.

**Comment by mart1ver** [comment]
problème réglé  c'est la derniere fois que je pousse direct ans dev promis axel

**Comment by darnuria** [comment]
voir #171
