### ISSUE TITLE
Fournir un script minimal pour HTTPS

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#181]
On pourrais fournir un script pour utiliser [CertBot](https://certbot.eff.org/) et l'EFF qui utilise Let'sEncrypt ce qui permettrais aux administrateurs de deployer Oressource avec HTTPS.

Vu que on souhaite que les données soient propriété des ressourceries proposer une solution de chiffrement pour le dialogue avec Oressource me semble bien.

**Comment by sebastiendarocha** [comment]
Salut,

c'est plus de la responsabilité de l'admin du serveur que des développeur du programme. En plus ce script forcerai les utilisateurs à utiliser la distrib prevue dans le script et le serveur web.

Imagine que tu fasses un script pour ubuntu16.04/apache2.2/php7.0/mariadb. bon, moi j'aime pas trop apache et j'ai une debian  stretch: le script marchera pas du tout : le paquets sont pas exactement les mêmes. Sous CentOs c'est encore pire :-(

Après je suis d'accord le https c'est un peu vital. Déjà et surtout parce que oressource a des mots de passe utilisateurs et que souvent ils utilisent le même partout.

Y a un autre truc c'est que certbot fonctionnera que si le serveur est accessible depuis internet, sinon l'infra let's encrypt ne fournira pas de certificats https. J'imagine que la plupard des installes sont en local.

Est-ce que vous voulez que j'ecrive un tuto sur l'installation de certificats https avec certbot avec nginx sur debian stretch ? je peux aussi faire une variante avec des certificats auto signés, c'est moins cool pour les utilisateur mais plus facile pour l'admin

**Comment by darnuria** [comment]
@sebastiendarocha Hello merci d'avoir pris le temps de répondre!

Je comprends bien les soucis d'administration... Le soucis c'est que les Oressources ont rarement un administrateur dédié :cry: il faudrait trouver une solution qui puisse être un bon compromis.

Pour la documentation je plussoie sans aucun soucis l'absence de documentation en français et accessible est un frein.



Dans tout les cas on pourras aussi réfléchir au plus long terme comment facilité le déploiement ça sera de bonne guerre vu qu'on cible maintenant `PHP 7.0` minimum :smile:.

PS: Pour « Let's Encrypt » oui c'est un vrai soucis l’accès à internet. Pour les ressourceries avec un réseau déconnecté d'internet un auto-signé serait bien si les navigateurs sont bien configuré ensuite bien entendu.

**Comment by sebastiendarocha** [comment]
J'avoue que je ne sais pas trop comment gérer proprement  et simplement un certificats auto signé côté client.

Je vais étoffer un peu la doc d'install pour expliquer comment faire let's encrypt sur une machine hébergée chez OVH/Online ou un certificat auto-signé quand la machine est sur un réseau local sans accès depuis le net. Ca pourra faire l'objet d'un script plus tard. 

Je rajouterais peut-être un chapitre sur comment utiliser nginx/php-fpm, c'est moins important.

J'essaye de faire ça dans la semaine.

++

**Comment by darnuria** [comment]
@sebastiendarocha Pour les certif clients tu peux faire proprement sous linux en configurant un firefox puis en poussant ce dernier dans le `/etc/skell/.mozilla` comme ça tout les utilisateurs crées d'un poste ou sur `NFS`+`LDAP` auront une copie de celui dans `/etc/skell`.

Donc si tu as configuré correctement à la « main » un Firefox les autres le seront si tu copie son `~/.mozilla`. Sous windows j'ai pas explorer, sous MacOSX non plus.

Sinon tu étuque tes utilisateurs.

Pour `php-fpm` c'est pas urgent c'est pas la solution utilisé en général (malheureusement). Pour le serveur web j'essaierais d'écrire la doc pour `apache2`

**Comment by darnuria** [comment]
Je ferme l'issue et écrirais de la documentation à l’occasion de la sortie de la version `0.2.0` sur comment utiliser https avec `nginx` ou `apache` et `php-fpm`.
