### ISSUE TITLE
Parametrage horaires

### ISSUE THREAD

**Issue by Recyclodrome** [mart1ver/oressource#182]
Bonjour, nous voudrions savoir comment mettre à jour les horaires sur Oressource. En effet il y a un écart d'environ 11h30 entre le logiciel de caisse en boutique et notre logiciel au bureau. 
Par exemple,  la boutique ouvre le mercredi 5 avril à 10h ; Au bureau, les ventes apparaissent avec un décalage de -11h30, soit le mardi 04 avril à compter de 22h20. Ce qui fausse les bilans par journées de ventes.
Nous avons débranché nos matériels électriques pendant plusieurs heures car nous faisions des aménagements dans le bureau. Ceci doit expliquer l'accroissement du décalage.
Comment faire pour mettre à jour l'horloge?

**Comment by darnuria** [comment]
@Recyclodrome Hello, votre analyse est bonne c'est bien la coupure temporaire d'électricité qui a causé le décalage de l'horloge du RasberryPi. 

Je vois avec @mart1ver ce matin pour qu'on vous propose la solution la plus simple on à déjà eu le soucis.

Explication:
En effet le RasberryPi ne possède pas d'horloge a pile comme les PC donc sans réseau connecte  internet si il est éteint il perd la date actuelle.

Note: si Martin vous à déjà dépanner au téléphone ne tenez pas compte de ce message.

**Comment by Recyclodrome** [comment]
Bonjour, merci pour votre réponse, on attend vos retours.
Giulia

**Comment by Recyclodrome** [comment]
Bonjour,

nous avons rencontré un nouveau souci en OR: des sauts entre les numéros de vente. Ce qui nous empêche de clôturer comptablement les journées de vente. A mardi pour en parler !! Cdlm G.

**Comment by Recyclodrome** [comment]
Bonjour,
bonnes nouvelles: finalement mercredi dernier 17/5 les horaires OR boutique se sont paramétrés à la bonne date et heure!!! merci ! cdlm

**Comment by darnuria** [comment]
Parfait c'est vrai que si le RaspberryPi perds la connexion au réseau et donc à Internet, il perd l'heure il ne possède pas d'horloge pour garder une trace du temps comme un pc traditionnel.

Du coup une panne électrique peut donner des soucis pareil.

Pour la non continuité entre les numéros de vente on va investiguer dans le code avec @mart1ver et si on arrive à répéter on avisera.

Merci d'avoir pris le temps d’ouvrir un ticket je ferme vu que c'est résolu a la prochaine!
