### ISSUE TITLE
Ne pas pouvoir encaisser si un objet est en cours de vente sans avoir été ajouté

### ISSUE THREAD

**Issue by vinfent** [mart1ver/oressource#20]
Il nous est arrivé d'avoir un doute sur certaine vente, si l'objet à été ajouté ou pas. Y'allah

**Comment by mart1ver** [comment]
problème résolu cependant possible confusion au moment d'un refus d'encaissement : il faut que les champs renseignant la quantité et le prix de objets soient obligatoirement vides ou egaux a zero...
