### ISSUE TITLE
Rendre signable le ticket de collecte

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#24]
Adapter le ticket de collecte de manière à pouvoir le faire signer par le donateur.
[edit @darnuria]

**Comment by mart1ver** [comment]
les trois tickets sonts a revoir

**Comment by darnuria** [comment]
@mart1ver Toujours d'actualité?

**Comment by mart1ver** [comment]
toujours oui, demandé par certaines structures pour un suivi "fiches de police" (comme dans les dechetteries)

**Comment by darnuria** [comment]
J'ai essaye quelque chose faut voir si cela conviendra ça arrivera avec la prochaine PR de la refonte des sorties.

**Comment by darnuria** [comment]
Idéalement on pourrais imprimer les collectes/sorties/ventes avec un code bar qui représente un hash de l'id + la date pour faire encore plus traçable.

**Comment by mart1ver** [comment]
definitivement plus d'actualié
