### ISSUE TITLE
POLICE DES CATÉGORIES PLUS GRANDE 

### ISSUE THREAD

**Issue by vinfent** [mart1ver/oressource#25]
Bonjour,

nous autres techniciens, nous avons tendance à avoir de gros doigts, potelés pour certains.

Serait-il possible d'avoir le menu déroulant des catégories avec des police plus grande, ou un espace plus marqué entre les différentes sous parties du menu déroulant?

Oui, nous avons un écran 17 p. et oui, nous sommes déjà au maximum du zoom...

Merci

**Comment by mart1ver** [comment]
fait
