### ISSUE TITLE
[critique] Se mettre en concordance avec SQL en mode strict.

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#270]
On oublie de renseigner l'id de l'utilisateur qui en crée une ressource dans la base.
Et attention aux `GROUP BY`.

À lire sur le sujet:
- https://mysqlserverteam.com/mysql-5-7-only_full_group_by-improved-recognizing-functional-dependencies-enabled-by-default/
- https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

**Comment by mart1ver** [comment]
https://mysqlserverteam.com/mysql-5-7-only_full_group_by-improved-recognizing-functional-dependencies-enabled-by-default/

**Comment by mart1ver** [comment]
https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

**Comment by darnuria** [comment]
https://github.com/mart1ver/oressource/pull/286
