### ISSUE TITLE
J'fais l'BILAN

### ISSUE THREAD

**Issue by vinfent** [mart1ver/oressource#30]
Yo Martin,

Petit récap concernant la maj des bilans: 
1) beau boulot, ça devient ergonomique et tout et tout
2) Ce serait génial de pouvoir avoir toujours le même ordre de catégorie dans le tableau, voir de pouvoir le choisir une fois pour toute ds "Gestion de la typologie des objets collectés", histoire de pouvoir avoir toujours le même export dans son tableur.
3) panier moyen: 2 chiffres après la virgule suffisent
4) Nombre de chèque et totale € en chèque par bilan 
5) Depuis la MAJ, j'ai eu 2x le même bug. Les infos en haut de mon ticket (asso, n°siret, adresse, tatati, tatata) ont disparue de mon ticket dans l'espace de vente. Problème solutionné les 2 x en allant dans onglet gestion / point de vente (les infos étaient tjs là), modifier puis ok, et comme par magie, les infos étaient de nouveau sur mon espace de vente.

Bon courage coco et encore bravo pour tes améliorations. 

PS: pour info, on va installer AGORA Project chez notre hébergeur de site, marsnet. Youpi

**Comment by vinfent** [comment]
Je viens de me rendre compte que dans le bilan, le nombre d'objets vendus et le nombre de vente est identique... donc petit bug.

Courage

**Comment by darnuria** [comment]
Hello, je fait le tri dans les tickets ce bug est-il encore d'actualité?

Vu la date d'ouverture je préfère te demander si il est nécessaire de ré-ouvrir le ticket
Je reprends ta liste et corrige moi. :)
- [x] Amélioration de l'ergonomie.
- [ ] Ce serait génial de pouvoir avoir toujours le même ordre de catégorie dans le tableau, voir de pouvoir le choisir une fois pour toute dans "Gestion de la typologie des objets collectés", histoire de pouvoir avoir toujours le même export dans son tableur.
- [ ] Panier moyen: 2 chiffres après la virgule suffisent.
- [ ] Nombre de chèque et totale en € en chèque par bilan.
- [ ] Les infos coordonnées de l'association en haut de mon ticket  ont disparue de mon ticket dans l'espace de vente. Problème solutionné allant dans onglet gestion / point de `ventemodifier` puis OK, et comme par magie, les infos étaient de nouveau sur mon espace de vente.
