### ISSUE TITLE
Faire une pagination pour les de verification de sorties/ventes/collectes

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#32]
Martin:
> L'idée c'est d'afficher les résultats des vérifications des saisies par pages de 100 résultats ce qui 
> éviterai de trop tirer dans la base à chaque chargement de ces page.

Axel:
> On pourrais même faire ça au scroll dans la page en JavaScript pour faire plus ergonomique.
> Idéalement avec une API paginée pour demander les données 100 par 100 ou 200 par 200.

[editition par @darnuria]

**Comment by darnuria** [comment]
@mart1ver Peut-on fermer ce ticket?

**Comment by mart1ver** [comment]
désolé pour le ticket peut explicite, l'idée c'est d'afficher les résultats des verif. des saisies par pages de 30 résultats (n résultats ) ce qui éviterai de trop tirer dans la base à chaque chargement de ces page (à plus de 300 résultats la page est hard-core à lire en plus)

**Comment by mart1ver** [comment]
afficher les tables avec https://datatables.net/(ou similaire) dans les verif. librairie potentiellement intéressante du coté des  bilans aussi

**Comment by darnuria** [comment]
De mon coté j'aime bien [handsontable](
https://docs.handsontable.com/0.31.1/tutorial-introduction.html) on peux vraiment bien customiser ça en CSS en plus faire un truc qui récupère des résultats à la volée depuis le serveur sur l’événement de scroll de la souris c'est pas trop infernal à faire une fois qu'on aura une API JSON qui tourne bien genre:
```
-> GET https://localhost/api/collectes&page=0
et on recupére notre collecte plus le lien de la prochaine page par exemple.
{
    "data" : [
        {  data item 1 with all relevant fields    },
        {  data item 2   },
        ...
        {  data item 100 }
    ],
    "paging":  {
        "previous":  null 
        "next":  "http://api.example.com/foo?page=1"
    }
}
```

**Comment by darnuria** [comment]
En lien avec https://github.com/mart1ver/oressource/issues/129 et https://github.com/mart1ver/oressource/issues/154

**Comment by darnuria** [comment]
Bon coté fun avec #286 pour les bilans de collecte ça rame plus pour l'ensemble de la base de la Rockette. ;p
