### ISSUE TITLE
tests branche dev au 30 janvier 2018

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#325]
subsiste encore quelques petits soucis : 

 - [x] voir 921deb7d491580abd835516a4686b276b91e786a pas d'encaissement aux ventes (avec ou sans pesées, avec ou sans antidate...), pas de message d'erreur `js` ni `php` @darnuria HELP
- [x] voir 96f41b48bdcd559ea4b6cbd36de1e43d8475126d `viz_caisse.php` plante du coté `php`:
![image](https://user-images.githubusercontent.com/7695290/35580612-cfc15edc-05e9-11e8-9c52-4762754134a1.png)
 petit soucis de requête `sql` à priori...
- edition_localites.php
![image](https://user-images.githubusercontent.com/7695290/35581608-961399ea-05ec-11e8-85f7-9e78e8e7fc53.png)

Voila, après ces trois bugs il ne vas pas rester grand chose, j'ai beau secouer le cocotier ya plus rien qui tombe....

**Comment by darnuria** [comment]
Hello @mart1ver ! Je jette un œil rapidement! :)

**Comment by darnuria** [comment]
Je suis dessus je fini le commit demain matin ou soir.
- Pour le premier point c'était des typo
- Le second c'était plus complexe je fait le fix
- Le dernier pas encore vu

**Comment by darnuria** [comment]
Pour le dernier point vérifie ta base de donnée il dois te manquer le champ sans faire express je l'avais sauté dans un script sql c'est possible que tu coup tu ne l'ai plus. Tu peux faire une capture d'écran de ton schema de `localites`?

**Comment by mart1ver** [comment]
yeah
