### ISSUE TITLE
test branche dev 22 mai

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#326]
les ventes par lots ne fonctionnent que sur le ticket, pas en enregistrement dans la base

les champs de la page utilisateurs.php s'autoremplissent , ils ne devraient pas:

**Comment by vtexier** [comment]
J'ai tenté une installation à partir de zéro avec la branche master : les ventes ne s'enregistrent pas.

J'ai fait une installation avec la branche de dev : 
* Le fichier oressource.sql n'est pas à jour. Il ne contient pas toutes les modifications des autres scripts sql. (Manque le champ "lot" dans la table "vendus" notamment).
* Une fois mis à jour, les ventes semblent fonctionner.

Il faudrait mettre à jour le fichier oressource.sql sur la branche dev.

**Comment by darnuria** [comment]
Super! Merci pour les retours! Hésite pas si tu vois d'autres trucs

Je prends note et essaye de faire un commit d'ici ce week-end c'est les examens pour moi cette semaine!

On a commencer à faire les derniers correctifs avant une version bien clean.

- Reste à faire des scripts pour récupérer des erreurs sur la base (en tout cas ce qu'on a trouvé dans la base à la rockette en testant a minima)
- Refaire le gestionnaire de tickets de caisse pour les ventes comme celui des sorties/collectes.
- Corriger un ou deux bugs de bilans

**Comment by vtexier** [comment]
Pour le commit, rien ne presse !

Pour la database, je pense que vous devriez suffixer le fichier oressource par un numéro de version correspondant à la version de la release.

Faire du versioning sémantique pour le code.

Vous connaissez https://flywaydb.org/ ? Très pratique les sql de migration avec numéro de la version du code correspondant.

**Comment by darnuria** [comment]
@vtexier Désolé du retard tu as écris quand j'étais en pleins partiels! :)
Ouaip je vais surement faire ça. On va essayer d'adopter le (versionnement semantique)[https://semver.org/] pour que ça fasse vraiment sens.

Pour FlywayDB, c'est pas forcément stupide je vais jeter un oeil.

Merci pour les retours. Si tu as le temps hésite pas à tester dev en install fraiche et en mise à jour d'une base on aimerais faire une version pour mi-septembre du retour serait fort appréciable!
