### ISSUE TITLE
Introduction progressive de composants React.js

### ISSUE THREAD

**Issue by yvan-sraka** [mart1ver/oressource#340]
Pas besoin de build-system / JSX pour commencer : https://reactjs.org/docs/add-react-to-a-website.html#add-react-in-one-minute

**Comment by darnuria** [comment]
Ayant bien les main dans le cambouis je vois bien la limite du model actuel pour faire une interface très interactive... On fait vite du code spaghetti impossible a maintenir, je suis donc ouvert à des propositions alternatives.
