### ISSUE TITLE
L'interface de collecte ne marche pas avec Firefox

### ISSUE THREAD

**Issue by daamien** [mart1ver/oressource#38]
sur la page ifaces/ collecte.php : les quantités ne se mettent pas à jour dans la partie "Bon d'apport".

ça fonctionne parfaitement avec Chrome donc je soupçonnne un problème de javascript quelque part.

**Comment by daamien** [comment]
Après recherche c'est la fonction  .innerText qui est utilisée pour modifier la valuer des champs du Bon d'apport. 

Le problème c'est que .innerText n'est pas standard et pas supporté par Firefox 

http://stackoverflow.com/questions/1359469/innertext-works-in-ie-but-not-in-firefox

Je pense qu'il vaudrait mieux utiliser directement JQuery pour modifier cette valeur

**Comment by darnuria** [comment]
@daamien : Ce bug à été corrigé sans JQuery dans le commit: 7268a4cc3daf2c0a3bfc02e3bebb1f938a5bf5b5 qui est dans la PR #64.

ll à été intégré à la branche de développement `dev` et devrait arriver dans master prochainement si aucune régression n'a été trouvée. :)

**Comment by daamien** [comment]
Merci beaucoup ! Je teste ça demain

**Comment by darnuria** [comment]
Si tu rencontre un soucis reporte le nous. ;)

**Comment by darnuria** [comment]
Attention! On a du réécrire l'histoire dans la branche `dev`. Je te conseille de détruire ta branche locale `dev` et de re-tirer `dev`. Encore désolé pour le dérangement.

**Comment by daamien** [comment]
ça marche c'est parfait

Merci beaucoup

**Comment by darnuria** [comment]
Merci noté comme résolut alors. :)
