### ISSUE TITLE
Bug dans la prise en compte des lots

### ISSUE THREAD

**Issue by HoverEpic** [mart1ver/oressource#380]
Bonjour, ma ressourcerie (La Charpentière, 37000 Tours) commence à prendre en main le logiciel, pour le moment je n'ai qu'un seul bug à signaler, je vais en faire une description complète.

La prise en compte des lots sur la page caisse se passe bien, mais lorsque l'on vérifie les ventes, le total de la ligne de vente en lot est égal à la quantité * prix, alors qu'il devrait être le prix total du lot (comme indiqué dans le total de la page caisse).

Si vous avez besoin de plus de détails, je suis a votre entière disposition.

Vincent.

**Comment by darnuria** [comment]
Hello, c'est sur quelle branche actuellement. On a eu un gros chantier la dessus et j'exclu pas avoir fait une petite étourderie... :|

Je pense que c'est ici:

[ifaces/verif_vente.php#L48](https://github.com/mart1ver/oressource/blob/master/ifaces/verif_vente.php#L48)
```

  $req = $bdd->prepare('SELECT
    ventes.id,
    ventes.id_createur,
    ventes.last_hero_timestamp,
    ventes.timestamp,
    ventes.id_last_hero,
    ventes.commentaire,
    moyens_paiement.nom moyen,
    moyens_paiement.couleur,
    SUM(vendus.prix * vendus.quantite) vente,
    SUM(vendus.quantite) quantite,
    SUM(vendus.remboursement * vendus.quantite) remb,
    SUM(pesees_vendus.masse) masse
  FROM ventes
  INNER JOIN moyens_paiement
  ON ventes.id_moyen_paiement = moyens_paiement.id
  INNER JOIN vendus
  ON vendus.id_vente = ventes.id
  LEFT JOIN pesees_vendus
  ON pesees_vendus.id = vendus.id
  WHERE ventes.id_point_vente = :id_point_vente
  AND DATE(ventes.timestamp) BETWEEN :du AND :au
  GROUP BY ventes.id,
    ventes.id_createur,
    ventes.last_hero_timestamp,
    ventes.timestamp,
    ventes.id_last_hero,
    ventes.commentaire,
    moyens_paiement.nom,
    moyens_paiement.couleur');
  $req->bindParam(':id_point_vente', $numero, PDO::PARAM_INT);
  $req->bindParam(':du', $time_debut, PDO::PARAM_STR);
  $req->bindParam(':au', $time_fin, PDO::PARAM_STR);
  $req->execute();
  $data = $req->fetchAll(PDO::FETCH_ASSOC);
```

J'avais fait dans [core/requetes.php#L521](https://github.com/mart1ver/oressource/blob/master/core/requetes.php#L521) un truc pas très glorieux comme ça.

```php
/// HACKME: Fonction contenant le code SQL pour gérer les lots.
/// TODO: Trouver une meilleure méthode.
function vendus_case_lot_unit(): string {
  return "case when vendus.lot > 0
  then vendus.prix
  else vendus.prix * vendus.quantite end";
}

// [...]
function bilan_ventes(PDO $bdd, string $start, string $stop,
  int $id_point_vente = 0): array {
  $cond = ($id_point_vente > 0 ? " AND ventes.id_point_vente = $id_point_vente " : ' ');
  $sql = "SELECT
    COUNT(DISTINCT(ventes.id)) as nb_ventes,
    SUM(" . vendus_case_lot_unit(). ") as chiffre_degage,
    SUM(vendus.quantite) as vendu_quantite,
    SUM(vendus.remboursement) as remb_somme,
    SUM(case when vendus.remboursement > 0 then 1 else 0 end) as remb_quantite,
    COALESCE(SUM(pesees_vendus.masse), 0) as vendu_masse
  FROM ventes
  INNER JOIN vendus
  ON vendus.id_vente = ventes.id
  LEFT JOIN pesees_vendus
  ON vendus.id = pesees_vendus.id
  WHERE DATE(ventes.timestamp) BETWEEN :du AND :au $cond";
// [...]
```

Dans l'idéal il faudrait rajouter un petit indicateur de si la vente est au lot en plus et utiliser ce hack qu'en pense tu? Si ça te va je peux tenter de faire ça d'ici ce weekend ou t'accompagner dans le bug.

**Comment by HoverEpic** [comment]
Je devait être la branche upstreaming/docker, qui était à jour avec master sur mon fork, mais comme je me suis rendu compte que je n’étais pas forcément à jour avec le repo de base, je vais tout re-tester. Je pense qu'on peut fermer l'issue pour le moment étant donné que je ne sais plus du tout ou en était le repo au momoent ou j'ai mis en prod.
Enfin bref, c'est un beau merdier de travailler avec des forks de forks... je ne me ferai plus avoir.

**Comment by HoverEpic** [comment]
Bon, je viens de tester avec la branche dev, l'erreur est toujours là, je n'ai pas la tête à me mettre dans le code ce soir, je regarderai quand je serais un peu plus libre.
L'idée de rajouter une colonne est bonne, l'information est à stocker (ou alors on considère les unité et les lots de la même façon et c'est le caissier qui fait le calcul).

**Comment by darnuria** [comment]
Yep je pense qu'on peux ajouter un `<tr>` pour dire si on est sur un lot ou unité et reprendre le code de calcul déjà utilisé dans les bilans. Si tu veux je peux faire le patch ou alors je te mentore comme tu sens! :)

**Comment by HoverEpic** [comment]
Pas de problème, je ferais ça quand je serais plus tranquille.

**Comment by HoverEpic** [comment]
J'ai ajouté la correction dans la PR #382 , tu pourras cherry-pick le commit 5e971ba1fbd4d9f26c6488a4473403e01311c613 sur master après le merge de dev.

**Comment by darnuria** [comment]
Fixé par le merge #382.
