### ISSUE TITLE
Vider le champ commentaire à la fin d'une vente

### ISSUE THREAD

**Issue by HoverEpic** [mart1ver/oressource#384]
Contexte : mon association se sert d'Oressource pour comptabiliser les ateliers et les adhésions (en plus de la vente des produits), le champ commentaire est utilisé pour indiquer l'atelier ou le nom et le numéro d'adhérent.
La vente est validée, la nouvelle vente commence mais le champ commentaire reste avec l'ancien commentaire. Si le caissier manque de vigilance, le commentaire est appliqué aux ventes suivantes.

J'ai essayé de voir si cela ne viens pas de l'auto remplissage des formulaires du navigateur, mais cela ne semble pas être le cas.

Ça fait un moment que je n'ai pas bossé sur Oressource, je ne sais pas trop ou trouver ça, mais je vais chercher et proposer un patch.

**Comment by darnuria** [comment]
Hello toutes mes excuses pour le délais de réponse déplorable période des examens et soutenances puis corrections pour mes étudiants ça m'a un peu coupé du monde. :)

Du coup si tu souhaite écrire une PR c'est pas très dur!

La page `vente` n'est pas rechargée à la fin de la transaction elle est «remise à zéro» par le JavaScript car on envoie les ventes, sorties et collectes au format JSON (à terme si j'avais le temps faudrait que tout soit géré par une petite API JSON...).

Du coup la fonction javascript ou tu peux écrire la ligne pour reset le commentaire est ici: [reset() vente.js L141](https://github.com/mart1ver/oressource/blob/master/js/ventes.js#L141)

Pour changer la valeur ça sera un simple accès par id avec `document.getElementById()` puis tu pourras mettre la propriété à `''` la chaine vide, c'est une ligne de code environ ^_^.

Si tu veux plus d'aide demande moi! :)

## Documentation

- [MDN document.getElementById()](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById)
- [MDN input.value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefvalue)

**Comment by HoverEpic** [comment]
Bonsoir, merci de ta réponse, j'ai surtout posté ça pour m'en rappeler =P
On m'a remonté d'autres erreurs depuis (encore sur les lots, mais cette fois au niveau des vérifications), il faudra que je m'y penche.
Pour le moment je bosse sur mon fork.
