### ISSUE TITLE
vendus id déjà existante en base de donnée insertion impossible

### ISSUE THREAD

**Issue by floppy31** [mart1ver/oressource#419]
Salut, 
je gère l'hébergement d'un oressource pour la ressourcerie de foix.
J'ai dû changer de serveur, et j'ai fais un upgrade vers debian 10. Avec la montée de PHP (il me semble que c'était à cause de ça) j'ai du faire un upgrade de oressource. J'ai bien appliqué correctement les correctifs sqls sauf erreur de ma part...
Actuellement j'ai cette erreur
```
2020/11/29 18:43:45 [error] 6218#6218: *2884274 FastCGI sent in stderr: 
PHP message:
PHP Fatal error: 
Uncaught PDOException: SQLSTATE[23000]:
 Integrity constraint violation:
1062 Duplicate entry '41568' for key 'PRIMARY' in oressource/api/ventes.php:110
Stack trace:
#0 XXX/api/ventes.php(110): PDOStatement->execute()
#1 XXX/api/ventes.php(177): pesee_vendu_insert(Object(PDO), 41568, Array)
#2 {main}
```
ça se passe quand j'essaye de rentrer plusieurs articles dans "vente" (quand il n'y en a qu'un ça marche)
(je précise que je ne connais pas ni le métier ni php, je ne suis pas non plus un crack en mysql)
Si quelqu'un pourrais me donner la solution pour que leur truc remarche ça serait super sympa pour eux ! 
Merci 
(si c'est plus simple pour vous par tel on peut s'appeller)

**Comment by darnuria** [comment]
Hello! Merci pour ton issue, oui on a bien fait une monté en version php 7.3 si je dit pas de bêtise côté le problème... Je suspecte que des trucs pas très nettes ont eu lieu en base du type plusieures ventes ont la même id...

Ici la vente d'id `41568` semble être plusieurs fois en base.

peut tu m'envoyer ce qui est est envoyé au serveur via la console de debug network et tu m'envoie ce qui est dans `Request` en gros ce que Oressource envoie au serveur?

Raccourci : `Ctrl + Shift + E`, une requête en post envoyé après avoir valider le panier le contenu de la vente dans l'UI.
Doc: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

![image](https://user-images.githubusercontent.com/2827553/100556774-e43a8d80-32a4-11eb-92e0-d410f4b2acb9.png)

**Comment by darnuria** [comment]
Ça resemble a une bidouille historique qui fait que les clefs etrangères sont.... pas des clefs quoi il y a des doublons d'ID dans les vendus :/

Tu peux me sortir ce que contiens la table `pesees_vendus` pour l'id `41568`

```sql
Select * from vendus where id = 41568;
```
et
```
Select * from pesees_vendus where id = 41568;
```

**Comment by darnuria** [comment]
Ok j'ai évaluer c'est bien un bug chez nous
```
[Mon Nov 30 01:08:45 2020] 127.0.0.1:48300 [500]: POST /api/ventes.php - Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '24' for key 'PRIMARY' in /home/darnuria/Oressource/oressource/api/ventes.php:110
Stack trace:
#0 /home/darnuria/Oressource/oressource/api/ventes.php(110): PDOStatement->execute()
#1 /home/darnuria/Oressource/oressource/api/ventes.php(177): pesee_vendu_insert()
#2 {main}
  thrown in /home/darnuria/Oressource/oressource/api/ventes.php on line 110
```

**Comment by darnuria** [comment]
C'est très brut j'aimerais avoir du recul et vérifier ce qui est inséré en base mais j'ai ouvert une PR: https://github.com/mart1ver/oressource/pull/420

**Comment by floppy31** [comment]
git show
commit cdd4431bb357dba571f1f28bbf4e7f8fd443918c (HEAD -> master, origin/master, origin/HEAD)
Author: Axel Viala <axel.viala@darnuria.eu>
Date:   Sun Oct 25 12:34:02 2020 +0100

    Update version in version checker
----------------------------
etat base avant : pj1
![Capture d’écran du 2020-11-30 08-30-50](https://user-images.githubusercontent.com/31502160/100580662-a8c0b300-32e6-11eb-93c9-e4ad70684200.png)

------
je mets 1 ventes
requests
{"classe":"ventes","id_point":2,"id_user":1,"id_moyen":1,"commentaire":"","items":[{"id_type":1,"id_objet":112,"lot":false,"quantite":1,"prix":2,"masse":10,"name":"bijoux / beauté"}],"date":"2020-11-30"}
mais une nouvelle err apparait

2020/11/30 07:29:42 [error] 6218#6218: *2961114 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to is_allowed_vente_id() must be of the type int, null given, called in XX/oressource/api/ventes.php on line 158 and defined in XX/oressource/core/session.php:106
Stack trace:
#0 XX/oressource/api/ventes.php(158): is_allowed_vente_id(NULL)
#1 {main}
  thrown in XX/oressource/core/session.php on line 106" while reading response header from upstream, client: 188.165.209.39, server: oressource.ressourceriedefoix.fr, request: "GET /api/ventes.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.socket:", host: "oressource.ressourceriedefoix.fr"
2020/11/30 07:31:38 [error] 6218#6218: *2961353 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to is_allowed_vente_id() must be of the type int, null given, called in XX/oressource/api/ventes.php on line 158 and defined in XX/oressource/core/session.php:106
Stack trace:
#0 XX/api/ventes.php(158): is_allowed_vente_id(NULL)
#1 {main}
  thrown in XX/core/session.php on line 106" while reading response header from upstream, client: 80.214.75.166, server: oressource.ressourceriedefoix.fr, request: "POST /api/ventes.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.socket:", host: "oressource.ressourceriedefoix.fr"
etat de la base
---------------------
plusieurs commandes:
{"classe":"ventes","id_point":2,"id_user":1,"id_moyen":1,"commentaire":"","items":[{"id_type":1,"id_objet":112,"lot":false,"quantite":1,"prix":2,"masse":10,"name":"bijoux / beauté"},{"id_type":2,"id_objet":61,"lot":false,"quantite":1,"prix":3,"masse":10,"name":"accessoires"},{"id_type":3,"id_objet":62,"lot":false,"quantite":1,"prix":1,"masse":10,"name":"bibelots"}],"date":"2020-11-30"}
2020/11/30 07:31:38 [error] 6218#6218: *2961353 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to is_allowed_vente_id() must be of the type int, null given, called in XX/oressource/api/ventes.php on line 158 and defined inXX/oressource/core/session.php:106
Stack trace:
#0 XXoressource/api/ventes.php(158): is_allowed_vente_id(NULL)
#1 {main}
  thrown in XX/oressource/core/session.php on line 106" while reading response header from upstream, client: 80.214.75.166, server: oressource.ressourceriedefoix.fr, request: "POST /api/ventes.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.socket:", host: "oressource.ressourceriedefoix.fr"
2020/11/30 07:35:38 [error] 6218#6218: *2961757 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '41582' for key 'PRIMARY' in XXoressource/api/ventes.php:110
Stack trace:
#0 XX/oressource/api/ventes.php(110): PDOStatement->execute()
#1 XX/oressource/api/ventes.php(177): pesee_vendu_insert(Object(PDO), 41582, Array)
#2 {main}
  thrown inXX/oressource/api/ventes.php on line 110" while reading response header from upstream, client: 80.214.75.166, server: oressource.ressourceriedefoix.fr, request: "POST /api/ventes.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.socket:", host: "oressource.ressourceriedefoix.fr", referrer: "http://oressource.ressourceriedefoix.fr/ifaces/ventes.php?numero=2"

la base reste inchangée...

je comprends pas pourquoi il incrémente les ids en en sautant...
désolé, si j'ai pas été clair, je dois afk pendant un petit moment, j'ai fait vite

merci du coup de main

**Comment by darnuria** [comment]
L'increment en sautant c'est normal c'est car heureusement on fait un rollback si ça echoue.

**Comment by darnuria** [comment]
Ok vous etes sur la dernière release, je vais en faire une nouvelle avec ce fix prochainement.

**Comment by darnuria** [comment]
Pour le côté pesees vendus c'est presque corrigé.

Pour le soucis de point de vente faudrait que je creuse c'est etrange.

**Comment by floppy31** [comment]
petit up? si possible, car ils ont repris l'activité... Désolé d'insister.. Merci

**Comment by darnuria** [comment]
Je test dans le weekend, la période est lourde et ni moi ni martin percevont d'argent sur Oressource. Je travail pour coopaname et le weekend je suis en ce moment a la correction des copies pour mon cours de Rust a paris8.

Je vais me pencher dessus mais et merger sans avoir tester ni de retour c'est souvent la porte a casser encore plus. @IGLOU-eu a tester https://github.com/mart1ver/oressource/pull/420 avant hier, apparament ça fonctionne.

**Comment by darnuria** [comment]
Mais je comprends totalement la gêne j'exprime simplement que bon, faut manger comme on dit. Et le fix va être appliquer cependant du recul etait neccessaire

**Comment by floppy31** [comment]
Merci bcp j'avais pas fait gaffe que tu avais déjà produit un fix... je l'ai testé vite fait sur la manip où j'avais l'err ça semble bon... Ils testeront plus eux... Oui moi aussi je gère leur hébergement de façon bénévole je sais ce que c'est... Désolé pour le rappel, et je vous tiens au jus si j'ai des retours. Merci!

**Comment by darnuria** [comment]
No soucis, je comprends c'est compliqué les associations ahah.

**Comment by darnuria** [comment]
C'est poussé dans la branche principale! Hésite pas a tester et a me faire des retours.

**Comment by floppy31** [comment]
salut, merci pour la réactivité,
c'est fait j'attends leur retour et je te dis

**Comment by darnuria** [comment]
Je vois si j'ai le temps de faire une version d'ici ce weekend ;)
