### ISSUE TITLE
Mettre en place un acces a distance pour des ventes

### ISSUE THREAD

**Issue by Flowwo** [mart1ver/oressource#428]
Bonjour,
Je suis bénévole dans une Ressourcerie, le  coordinateur me demande si il est possible de configurer un accès à distance pour une boutique afin d'enregistrer les ventes/sorties.
Cela me semble possible, cependant en terme de sécurité l'adresse du serveur est en http est non en https. Je lui est proposé un vpn, mais cela reste payant pour en avoir un bon.

Avez-vous des conseils pour que je puisse configurer l'accès à distance de façons sécurisé ?

**Comment by darnuria** [comment]
Hello, si vous avez un certificat HTTPS et que vous avez correctement configuré le serveur web (Apache ou Ngnix) ça permet un accès «sécurisé», vu qu'on a jamais été audité je recommande quand même de mettre Oressource sur une machine virtuelle ou un ordinateur non critique et comme toujours de faire des backup et ne pas réutiliser les mots de passe.

Il y a pas de connexion avec un service de courriel donc pas de risque de spam après.

Je précise c'est du support bénévole, délivré "comme tel", comme le logiciel qui est distribué "comme tel". Éventuellement Martin de la petite rockette à la structure pour proposer des formations pour déployer Oressource de mémoire.

**Comment by Flowwo** [comment]
Bonjour Damurie,
Mercie pour la réponse et tes explications. Effectivement il faut un certificat https, cela coûte autant qu'un domaine. En analyse un peut plus l'installation à la ressourcerie et en installant un serveur de test chez moi, j'ai pu conseiller le responsable et donner ces informations. 
Concernant la version du serveur à la ressourcerie, elle date de 2017, est-ce qu'il est conseillé de le mettre à jour?

**Comment by darnuria** [comment]
> Concernant la version du serveur à la ressourcerie, elle date de 2017, est-ce qu'il est conseillé de le mettre à jour?

Alors si tu parle de l'OS (probablement Linux) oui pour vous éviter des gros problèmes, mais pensez faire des sauvegardes dans tout les cas.

Concernant Oressource, libre a vous, la mise a jour implique pas mal de changement sur la base de donnée a ne pas faire sur le serveur sans avoir tester avec une copie des données dans un environnement de test.

**Comment by darnuria** [comment]
> cela coûte autant qu'un domaine

Non pas obligatoirement: https://letsencrypt.org/

Il y a de quoi déployer un certificat HTTPS let's encrypt sur toutes les distributions linux ou même windows et MacOS.

**Comment by darnuria** [comment]
ah et a titre indicatif de 2014 a 2018 Oressource fonctionnais sur un Rpy a la rockette aucune idée de si ils ont continuer ainsi! :)
