### ISSUE TITLE
bilan collectes !

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#52]
afficher répartition (masse)  par type de collecte pour chaque typo d'objet

**Comment by darnuria** [comment]
Est-ce encore à faire?

**Comment by mart1ver** [comment]
oui!! , par ailleurs il y à tout plein de données à afficher dans les bilans , je pensse à tout ce qui est évolution dans le temps et comparaison de différentes périodes dans les bilans collecte mais aussi les autres.

**Comment by mart1ver** [comment]
fait depuis longtemps !
