### ISSUE TITLE
Problème récurent lors d'impression ticket de caisse

### ISSUE THREAD

**Issue by Recyclodrome** [mart1ver/oressource#57]
- Imprimé deux tickets EEE pour garanti avant encaissement et ligne d'encaissement disparu > impossible de savoir si encaisser ou pas > pas d'accès au fichier « vente boutique » > possible erreur de caisse >

C'est un retour direct des salariés. Si tu as besoin de plus d'explication pour comprendre la situation, je t'en donnerai.

Big up

**Comment by darnuria** [comment]
Hello, est-ce toujours d’actualité ou puis-je clore le bug?

**Comment by darnuria** [comment]
@Recyclodrome Je clos le bug pour faire le triage, n'ayant pas eu de réponse mais si le bug est toujours d'actualité tu peux ré-ouvrir le bug avec plaisir.
