### ISSUE TITLE
Fonction vente par lot défaillante

### ISSUE THREAD

**Issue by Recyclodrome** [mart1ver/oressource#58]
Salut Martin,

Du coup, pour avoir expérimenté la fonction "vente lot", je me suis retrouvé avec des erreurs de caisse au final ;-( Le problème vient du fait que cette fonction se permet d'ajuster au plus près de la somme voulu, sans l'atteindre totalement lorsque que ça ne peut pas tomber juste. Du coup, je me retrouve avec des nombres à virgules au lieu d'avoir des chiffres ronds ( voir journée de vente du 23-07-2015 par exemple)

Mon idée pour résoudre ce problème, serait que ton logiciel fasse en sorte que le dernier objet du lot fasse tampon pour qu'au final le prix du lot annoncé soit bien celui qu'on retrouve dans le bilan.

Si c'est pas clair, je t'explique en live.

Big up

**Comment by mart1ver** [comment]
bien vu, je vais opter pour ta solution

**Comment by darnuria** [comment]
Hello peux-on clore le bug ou c'est encore sur le feu? :) (je fait le tri des bugs mort-vivants pour y voir plus clair)

**Comment by mart1ver** [comment]
Ce bug est Bel et bien encore sur le feu ...

**Comment by darnuria** [comment]
Ok tu peux mettre une capture d'écran ou une procédure pour le reproduire? Vais essayer de me pencher sur les bugs en cours une fois qu'on à fait passer tout les gros changements.

**Comment by darnuria** [comment]
@Recyclodrome C'est en lien avec ça en fait https://github.com/mart1ver/oressource/issues/69

**Comment by darnuria** [comment]
Duplicata #69 résolution dans #229 et #232 On approche de la fin!
