### ISSUE TITLE
Remboursement inégaux

### ISSUE THREAD

**Issue by Recyclodrome** [mart1ver/oressource#60]
Salut, 

J'ai un problème avec mes remboursements du mois de septembre: #4613 / #4663 / #4768 / #5353 .

Le total de mes remboursements ne sont pas inclus dans mes totaux / rayon dans le bilan.

Big up

V

**Comment by darnuria** [comment]
@mart1ver Je sais plus si on en avait parler à la Rockette, tu as plus d'infos?

**Comment by Recyclodrome** [comment]
Je ne t'en avait pas parlé lors de ma visite. 

Le problème concerne les ventes de septembre: #4613 / #4663 / #4768 / #5353.

En gros:
- dans vérifier mes ventes, je trouve les bonnes sommes remboursées, 
- dans le regroupement par type d'objet, les sommes remboursées sont inexactes, 
- dans le bilan, sous la date, la somme remboursée est bonne.

Ce bug est problématique pour moi car je ventile mes ventes / rayon.

Big up

**Comment by daamien** [comment]
On dirait que c'est le même problème que le bug #86 non ?

https://github.com/mart1ver/oressource/issues/86
