### ISSUE TITLE
Feuille de routes améliorations etc...

### ISSUE THREAD

**Issue by darnuria** [mart1ver/oressource#66]
Quelques pistes.

Car comme tu l'a soulevé sur tes petits RasbperryPI parfois on ressent des ralentissements.

Serveur Web:
[Nginx](http://nginx.org/) (Ça marche chez moi ça consomme vraiment moins que Apache cool pour tes RaspberryPi).
~~Ou bien [Lighttpd](http://www.lighttpd.net/)~~

Méthode de dialogue avec l'Interpréteur PHP via FAST-CGI avec [PHP-fpm](http://php-fpm.org/) en lieu et place de mod_php qui est antique. Ou bien utiliser la [HipHopVirtualMachine](http://hhvm.com/).

Quelques recherches sur le sujet
https://www.howtoforge.com/tutorial/install-lighttpd-with-php-fpm-and-mysql-on-debian/
http://wiki.dreamhost.com/Web_Server_Performance_Comparison
https://www.wikivs.com/wiki/Lighttpd_vs_nginx

Pour SQL utiliser des index dans la base améliorera grandement les performances des requêtes. Ce [site](http://use-the-index-luke.com/fr/table-des-matieres) explique ça assez bien.

Pour les formulaires, voir si utilisé des requêtes [AJAX](https://en.wikipedia.org/wiki/AJAX)
(Asynchronous JavaScript and XML) ne serait pas plus pertinent que de faire du POST/GET.
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/Sending_forms_through_JavaScript

**Comment by darnuria** [comment]
Réfléchir à une version 2.
Solutions pour la partie backend.

Architecture: Utiliser un web-framework avec un moteur de template.

Scénarios pour les langages:
Langage à typage statique inféré:
[Scala](https://en.wikipedia.org/wiki/Scala_%28programming_language%29) et le framework web [Play](https://en.wikipedia.org/wiki/Play_Framework) ou [Scalatra](https://en.wikipedia.org/wiki/Scalatra).
**Avantages**: Stabilité, monté en échelle du projet aisée, erreurs fiables et attrapées avant la production, performances.
**Désavantages**: Connaissances en codes pour contribuer plus élevées, langage à apprendre, style de programmation à apprendre.

Langage à typage dynamique (ou graduel):
[Hack](https://en.wikipedia.org/wiki/Hack_%28programming_language%29)  
**Avantages**: pas besoin de tout recommencer c'est compatible avec PHP pour peu que l'on utilise la [HipHopVirtualMachine (HHVM)](https://en.wikipedia.org/wiki/HHVM), plus sur que Python ou Ruby via le typage optionnel qui limite les dégâts.
**Désavantages**: Langage très jeune, peu de bibliothèques en Hack pur, monté en compétence.

Solution en Front-end:
A étudier.

**Comment by daamien** [comment]
Pour donner un peu de feedback là dessus : il faudra déjà définir ce qu'on entend par "performances". Il me semble que le type d'usage du logiciel se limite à 2 ou 3 d'utilisateurs simultanés au maximum et des volumes de données inférieurs à 100Go. Dans ce contexte-là je ne suis pas sur que les améliorations seront visibles et surtout je ne crois pas que les utilisateurs sont en demande de performances. Pour caricatures, le mec ou la fille qui fait une collecte peut attendre 30 secondes que la page web s'affiche ça va pas lui pourrir sa journée... :-)

En revanche pour le choix du langage : je pense que le choix de JS + PHP + MySQL doit être conservé. Je suis pas spécialement fan de ces technos mais c'est simple d'accès, il y a des tonnes de docs sur internet et c'est le standard chez les hébergeurs. Du coup pour un outil comme oressource qui vise des utilisateurs qui ne sont pas informaticiens c'est important de ne pas partir sur des langages trop complexes. 

Le PHP c'est la garantie qu'ils pourront quand même l'auto-héberger, corriger des bugs, voire d'adapter à leur besoin. En tout cas quand on a fait le choix de Oressource pour notre ressourcerie, le fait que ce soit du PHP+MySQL était un argument positif. Et encore une fois je juge pas des qualités intrinsec des technos mais de leur facilité d'accès pour des ressourceries....

Si vous partez sur du Scala + MongoDB, vous allez vous éclater mais personne ne vous fera des corrections de bug et globalement les gens utiliseront l'outil comme une grosse boite noire incompréhensible....

**Comment by darnuria** [comment]
Merci d'avoir commenté mes `pistes de réflexion`/

Par performances j'entends nos usages en internes. On a foutu le projet sur un RaspberryV1. /o/

Serveur web:
L'objectif est de gagner un peu en mémoire en passant de Apache2(On utilise aucun module à vrai dire) à un serveur web plus léger. On a actuellement parfois des soucis ou ça passe sur la swap alors qu'on devrait pas.

Interpréteur PHP: Passer en FAST-CGI dans les configurations par défaut serait cool.

Base de donnée: MySQL/MariaDB c'est parfait rien à redire faudra juste repenser les tables et les rêquêtes pour utiliser des index.

Question data: Nous à la petite rockette on à bien 2ans de données c'est pas ouf mais ça grossis et on pense prendre en compte les pesées en vente ça va faire monter le volume mais rien de fou.

Pour les hébergeurs mutualisé qui ont toujours des gouts douteux quand aux technologies qu'ils proposent je sais bien que c'est limitant.

Un de mes objectifs est de bien séparer le client Web et le code coté serveur pour avoir plus de souplesse.

Une des pistes que j'avais pas noté serait de partir sur l'utilisation d'un framework PHP5+ super léger style http://www.slimframework.com/ ou https://phalconphp.com/en/. Histoire de nous simplifier la vie coté serveur.

Pour les taches bien gourmandes un peu propres à la petite Rockette au pire on pourras faire un projet annexe dans un autre langage qui expose une API et qu'on fait tourner à coté.

L'objectif n'est pas de tout refaire loin de la. :)

**Comment by daamien** [comment]
Merci pour ces réponses.

Quelques remarques pour faire avancer le débats 

__Architecture__

J'ai l'impression que c'était l'idée initiale avec les dossiers `moteur` et `ifaces`.  Je n'ai pas d'avis tranché sur la question mais je trouve que déjà que l 'utilisation d'un moteur de template (mustache, smarty, volt, twig, whatever) serait un premier pas intéressant. Actuellement une bonne partie du code PHP dans le dossier `ifaces` pourrait être simplifié et je pense que d'une manière générale ça aiderait de séparer l'extraction des données et leur affichage. Et dans un second temps, pourquoi pas utiliser un framework... Sachant que certains moteur de template sont compatibles avec des framworks, comme volt pour phalcon.

__Base de données__

Je préfère PostgreSQL mais l'utilisation de mysql ne me choque dans ce cas précis. 

Sur les index, j'ai regardé un peu et sur la plupart des tables c'est inutile... Les tables comme `utilisateurs`, `types_*`, `points_*` sont tellement petites qu'elles tiennent en RAM et l'index n'apportera rien. A priori, les seules tables qui auraient besoin d'index c'est `pesee_*`, `vendus`, `sorties` et peut-être `collectes` et `ventes`. Si vous pouvez donner ces chiffres, ça serait intéressant de connaitre la volumétrie de ces tables au bout de 2 ans.

Après il y a peut-être une réflexion à avoir sur l'archivage. Est-ce que toutes les données sont nécessaires à tout moment ? Est-ce qu'on ne pourrait pas archiver certaines infos après un certain temps ?

__ Pour les performances__

J'ai compris le besoin lié au Raspberry. De notre coté, on est plutot dans une réflexion inverse en se disant qu'on pourrait héberger plusieurs instances pour plusieurs ressourceries sur un serveur mutualisé et faire baisser les temps de maintenant et les couts...


__ Pour les pesées en vente __

C'est quelque chose qui est aussi sur ma To Do list et on m'a parlé d'une ressourcerie qui a un fork qui gère ça... A creuser.


__ Se rencontrer ?__

Bon comme je vois que la liste d'idées s'allonge à chaque itération, je me dis que ça pourrait être bien d'en discuter de visu. ça vous dit qu'on se voit pour en parler ?

**Comment by darnuria** [comment]
Réponses tardive, faute de beaucoup de boulot dans la ressourcerie. :)

_Architecture_
>Je n'ai pas d'avis tranché sur la question mais je trouve que déjà que l 'utilisation d'un moteur de template (mustache, smarty, volt, twig, whatever) serait un premier pas intéressant.```

Très clairement actuellement je travail dessus avec twig en local. J'attends d'avoir un retour de @mart1ver dans la fin de semaine pour rendre ça publique sur mon dépôt.
A terme j'aimerais que plus de choses soient gérées par le client JS(moderne >= ES6) + AJAX pour soulager le serveur sans pour autant alourdir le client.

> Actuellement une bonne partie du code PHP dans le dossier `ifaces` pourrait être simplifié et je pense que d'une manière générale ça aiderait de séparer l'extraction des données et leur affichage.

Ton idée à ce propos rejoins ce que je disais précédemment.

_Base de données_

> Je préfère PostgreSQL mais l'utilisation de mysql ne me choque dans ce cas précis.
Je connais pas `PostgreSQL` à l'occasion si tu viens à la Rockette tu pourrais nous en parler.


> Sur les index, j'ai regardé un peu et sur la plupart des tables c'est inutile... Les tables comme utilisateurs, types_*, points_* sont tellement petites qu'elles tiennent en RAM et l'index n'apportera rien.

Par contre ça apporte un coté ergonomique pour faire des relations et introduites de nouvelles tables si on voulait revoir certains détails de l'application.

>A priori, les seules tables qui auraient besoin d'index c'est pesee_*, vendus, sorties et peut-être collectes et ventes. Si vous pouvez donner ces chiffres, ça serait intéressant de connaitre la volumétrie de ces tables au bout de 2 ans.```

Pour la Volumétrie j'essaie de te trouver le bilan de la Rockette qui est sympa.

_Pour les performances_

>J'ai compris le besoin lié au Raspberry. De notre coté, on est plutot dans une réflexion inverse en se disant qu'on pourrait héberger plusieurs instances pour plusieurs ressourceries sur un serveur mutualisé et faire baisser les temps de maintenant et les couts...

Si on suppose de rester avec du PHP(moderne) l'idéal serait de réduire au maximum le rendu de page coté serveur et de tendre à terme vers une Application Web(en page seule ou multi-page) pour que le serveur ne serve qu'à servir des données et non à faire du rendu.

_Pour les pesées en vente_

> C'est quelque chose qui est aussi sur ma To Do list et on m'a parlé d'une ressourcerie qui a un fork qui gère ça... A creuser.

On va bosser la dessus dès qu'on à fait la grosse plomberie la franchement c'est compliqué d'ajouter de la logique sans tout casser.
Tu as l'URL du fork?

_Se rencontrer ?_

> Bon comme je vois que la liste d'idées s'allonge à chaque itération, je me dis que ça pourrait être bien d'en discuter de visu. ça vous dit qu'on se voit pour en parler ?

Mais carrément! J'essaie d'en parler avec @mart1ver demain.

**Comment by darnuria** [comment]
@daamien Je suis en train de réécrire un schema de DB propre pour passer à PostgreSQL et avoir une base solide pour la suite j'upload ça en gist tu me propose des commentaires et m'aide à écrire un script d'update?

**Comment by daamien** [comment]
Salut,

Je viens de voir ta proposition et ça me pose beaucoup de questions...

1- Je ne sais pas trop comment va fonctionner PostgreSQL sur un Raspberry Pi....  Il n'y aura pas de soucis pour l'installer mais au niveau perf je suis pas certain c'est l'inconnue... J'ai vue passer quelques benchmarks mais rien de très concret....

2- Le nouveau schema est assez différent du schéma actuel... C'est volontaire ?

3- Sur le passage en anglais, c'est effectivement une bonne pratique d'une manière générale pour un projet open source. Mais dans ce cas précis, est-ce que ça ne sera pas une barrière pour des salariés de ressourcerie qui voudraient modifier le logiciel ou ajouter une fonctionnalité ?

4- Même chose pour MySQL/MariaDB.... Encore une fois je suis pas fan mais ça reste le SGBD le plus accessible et le plus répandu chez les hébergeurs... Je pense qu'il faut se mettre dans la peau d'un salarié de ressourcerie qui doit installer et maintenir Oressource sans avoir beaucoup de temps à y consacrer...

Bref je suis pas fondamentalement opposé aux changements que tu proposes mais ça vaut la peine d'en discuter de visu je pense... J'ai envoyé un mail à Martin pour lui proposer une date... Par contre j'ai pas ton adresse mail, est-ce que tu pourrais me l'envoyer à damien@dalibo.info ?

**Comment by darnuria** [comment]
J'ai pris le temps de lire mais pas encore le temps de répondre je fait ça dès que possible.

**Comment by darnuria** [comment]
On reprends le nettoyage de printemps! -> https://github.com/mart1ver/oressource/issues/102
Je clos ici pour l'instant.
