### ISSUE TITLE
Arrondis dans les tickets des formulaires

### ISSUE THREAD

**Issue by mart1ver** [mart1ver/oressource#69]

**Comment by darnuria** [comment]
@mart1ver Pour corriger tu aimerais faire comment? On fait une division entière avec reste sur les lots et on ajoute deux objets en base pour éviter les arrondis infini comme  `1/3`?

**Comment by darnuria** [comment]
Bon vu que c'est encore d'actualité on pourrais en effet tout passer en nombres entiers décimaux ça demanderais de changer principalement du code serveur c'est pas irréalisable. On peux se dire que une fois le ménage terminé dans les sources on se met ça sous le coude.

**Comment by darnuria** [comment]
Comme dit plus haut je storm un coup la gui des ventes et on essaye de clore ça?

**Comment by darnuria** [comment]
@yvan-sraka C'est pas à prendre au pied de la lettre mais le bug était côté client avec l'utilisation de l'HTML comme support de donné et des appels à `parseFloat` et `toFixed`.
On va essayer de traquer ça une fois #131 passé.

**Comment by darnuria** [comment]
Piste données `POST envoyées au serveur actuellement:
```
antidate=2017-08-02
tid_type_objet1=8
tid_objet1=15
tquantite1=102
tprix1=0.000980392156862745 <---- Hmmmm
comm
moyen=1
nlignes=1
narticles=102
ptot=0.1
id_user=1
saisiec_user=oui
niveau_user=c1v1s1bighljke
id_point_vente=1
```

C'est assez normal. Diviser ou multiplier des flottants qui ont des ordres de grandeur différents mènent à ce genre de problèmes. On divise ici 0.10 par 102 bonjour la casse vu l’implémentation des flottants en hardware. :)

**Comment by darnuria** [comment]
Monétairement ça devrait faire `1/1020` euros.

**Comment by darnuria** [comment]
voir #229 et #232.

**Comment by darnuria** [comment]
Partiellement résolu dans dev. Prochainement totalement après modification des bilans toutes les pages utilisant des ventes.
