### ISSUE TITLE
Imprimer ticket a posteriori

### ISSUE THREAD

**Issue by Recyclodrome** [mart1ver/oressource#81]
Salut, 

Pour des raisons comptables, nous allons devoir imprimer systématiquement un ticket lors des paiements par chèque.

Serait-il possible de créer la possibilité d'imprimer un ticket d'une vente passée? 

Apparemment, le commentaire s'efface dans la base de donnée, lorsqu'on imprime un ticket. Sur le ticket, j'ai le commentaire mais plus dans la base de donnée.

Merci et Big Up

**Comment by darnuria** [comment]
Hello, le soucis est-il toujours d’actualité?

Si oui lors de la refonte (prochainement on fait les sorties et collectes la) j'irais jeter un œil.

**Comment by darnuria** [comment]
@Recyclodrome Encore d'actualité? Si oui tu peux réouvrir le bug.

**Comment by Recyclodrome** [comment]
Bonjour,

Vincent Lorin qui gérait le logiciel OR a quitté Recyclodrome. Pour 
l'instant on a personne de dédié sur ces aspects techniques du logiciel. 
Nous ne saurions donc répondre aux différents mails envoyés sur la 
clôture de bugs ou de bugs toujours d'actualité...

/Angélique GAULARD//
/*___________________________________________________________*
Association RECYCLODROME
/ressourcerie agréée par le Réseau des Ressourceries//
//www.ressourcerie.fr/ <http://www.ressourcerie.fr/>/

//notre boutique du 47 rue d'aubagne est ouverte de 10h à 19h//
//tous les mercredis et les 1ers et 3èmes samedis du mois de 10h à 
17h30//(sauf fermeture annuelle)//
/
21 rue Chateauredon - 13001 Marseille
09 54 246 246 (prix d'un appel local)
/www.recyclodrome.org/ <http://www.recyclodrome.org/>

/""Rien ne se crée, tout se transforme, à toi de donner de la forme""
François LORIN/
