### ISSUE TITLE
Le fichier moteur/dbconfig_exemple.php a disparu

### ISSUE THREAD

**Issue by Seba-Allis** [mart1ver/oressource#82]
Salut,

Le fichier d'exemple qui ouvre la connexion à la base de données a disparu.

Je le l'ai retrouvé en farfouillant dans le dépôt.

Je pense qu'un contributeur a dû renommé le fichier par inadvertance et dès qu'il soumet un patch le fichier saute.

Bonne journée

**Comment by daamien** [comment]
Corrigé ! C'est en attente d'acceptation
