### ISSUE TITLE
Impression ticket => bug applet

### ISSUE THREAD

**Issue by Recyclodrome** [mart1ver/oressource#84]
Bonjour,

Chez nous, on imprime des tickets pour nos chèques. Cela entraine un bug:
- impression efface le commentaire. 
- efface la date modifiée, pour mettre celle du jour de l'impression. Dans notre organisation, nous rentrons souvent les chèques ds Oressource un jour après la vente, donc, nous utilisons la fonction changer la date. Celle-ci s'enregistre automatiquement au Jour J et non au Jour J-1. 

Du coup, j'utilise PhP my admin pour remettre manuellement la bonne date.

J'espère que c'est clair.

Bon courage

V

**Comment by darnuria** [comment]
@Recyclodrome Encore d'actualité?
