### ISSUE TITLE
Sauvegarder la base de donnée

### ISSUE THREAD

**Issue by Recyclodrome** [mart1ver/oressource#87]
Bonjour, 

Cela fait un an et demie que nous utilisons ORessource. Pouvez-vous nous décrire la procédure pour enregistrer notre base de donnée, au cas où ça explose chez nous :-) 

Merci et bel été à vous

V

**Comment by daamien** [comment]
A ma connaissance, il n'est pas possible de sauvegarder les données depuis l'interface web.

La manière la plus simple de sauvegarder la base, c'est d'ouvrir la console et lancer la commande:

```
mysqldump -h localhost -u oressource -pZZZ oressource > /tmp/sauvegarde_oressource.sql
```

(en remplaçant ZZZ par le vrai mot de passe.)

Ensuite il faut récupérer le fichier ``sauvegarde_oressource.sql`` dans le  dossier ``/tmp``

**Comment by Recyclodrome** [comment]
Bonjour Damien, 

Merci pour ta réponse. Quand tu parles de mot de passe, il s'agit bien du mot de passe d'accès à la base par php my admin ?  Ne faut-il pas un espace entre -pZZZ ?

Voilà la réponse que terminal me donne lorsque je tape ta commande. Rassure moi stp, je ne prends aucun risque en faisant cette opération ? En installant ces paquets ?

Encore merci pour ton soutien

**Comment by Recyclodrome** [comment]
gestion3@gestionV3 ~ $ mysqldump -h localhost -u oressource -pHAHAHA oressource > /tmp/sauvegarde_oressource.sql
Le programme « mysqldump » peut être trouvé dans les paquets suivants :
 * mysql-client-5.5
 * mariadb-client-5.5
 * mysql-client-5.6
 * percona-xtradb-cluster-client-5.5
Essayez : sudo apt-get install <paquet sélectionné>

**Comment by daamien** [comment]
1/ Si phpmyadmin est installé alors tu peux faire une sauvegarde avec et c'est probablement la meilleure solution. Une fois connecté sur phpmyadmin, il suffit de cliquer sur la base oressource puis sur l'onglet "exporter". Une fois la page d'export, cliquer sur "executer" et ça téléchargera un fichier sql qui contient toutes les données. Si ça fonctionne comme ça pas la peine d'installer mysqldump.

Si tu veux quand meme installer mysqldump :

2/ Il ne faut pas d'espace entre ``-pZZZ`` mais on peut aussi mettre uniquement ``-p`` et taper le mot de passe en direct ensuite

3/ mysqldump est completement inoffensif :-) C'est un outil de sauvegarde ("dump") et ça exporte simple la base dans une fichier sans la modifier. Tu peux l'installer avec la commande ``apt-get install mysql-client``

4/ le mot de passe de la base se trouve dans le fichier moteur/dbconfig.php

**Comment by Recyclodrome** [comment]
C'est nickel, ça marche avec phpmyadmin. c'est simple et efficace. Quel est la procédure pour remettre en ordre de marche Oressource si par exemple notre serveur plante ? Ne faudrait-t-il pas sauvegarder tout ce qu'il y a sur notre petit serveur ? 

Tes conseils déchirent

**Comment by daamien** [comment]
Dans phpmyadmin, il y a un onglet "importer" qui fait le chemin à l'envers, c'est à dire que ça prend fichier SQL en entrée et ça réinjecte les données dans une base. 

La procédure que je conseille pour recharger les données c'est:

1- Renommer la base "oressource" existante en "oressource_inactive"
2- Créer une nouvelle base "oressource"
3- Sélectionner la nouvelle base "oressource"
4- Aller sur l'onglet "Importer" et uploader le fichier sauvegarde_oressource.sql

En théorie : sauvegarder la base de données c'est suffisant pour reconstruire une nouvelle caisse
En pratique : je conseille de sauvegarder en même temps tous les fichiers qui se trouvent le dossier /var/www  c'est peut faire gagner beaucoup de temps au moment de restaurer une vieille sauvegarde

Attention c'est important de stocker le fichier sauvegarde_oressource.sql en dehors du serveur Oressource. Par exemple sur une clé USB que vous rangez dans un endroit sur ou sur un autre ordinateur qui n'est pas dans la même pièce que la caisse. Comme en cas de vol ou de crash du serveur, votre sauvegarde est à l'abri dans un autre endroit

**Comment by Recyclodrome** [comment]
Nickel chrome. Bel été à toi
