### ISSUE TITLE
Rendre l'installation plus facile

### ISSUE THREAD

**Issue by daamien** [mart1ver/oressource#90]
- [x]  mettre admin/admin comme utilisateur initial
- [ ] supprimer les données de la Petite Rockette dans le fichier oressource.sql
- [x] créer un fichier install.php qui prend en entrée les paramètres de connexion MySQL et qui charge le schéma de la base

**Comment by darnuria** [comment]
> mettre admin/admin comme utilisateur initial`

Ou pourquoi pas faire un petit script shell ou php qui prépare un fichier de config(un array en gros) qu'on chargerais avec PHP?

Et qui propose de taper un nom d'admin/password un peu dans l'idée de mysql_secure_install en vraiment simple.

**Comment by daamien** [comment]
Je ne vois pas vraiment l'intérêt d'un script de configuration spécifique. Démarrer avec un ``admin``:``admin`` c'est un grand classique et ça ne pose pas vraiment de problème de sécurité car les installations Oressource ne sont pas exposées sur internet. 

A la limite, on peut détecter que le mot de passe n'a pas été modifiée et à la première connexion le rediriger vers l'interface de modification du mot de passe et de son profil utilisateur en général

**Comment by darnuria** [comment]
C'est vrai qu'on pourrais faire ça. Bon pour l'instant par contre on est dans les gros travaux pour améliorer les sources, régler les failles sur les entrées/sorties du coup on verra ça après.

On aimerais bien pouvoir passer dans master toutes les grosses améliorations en terme de code et d'ergonomie apportées aux collectes et aux sorties d'ici 2 semaines. (estimation optimiste)

**Comment by darnuria** [comment]
D'ailleurs on aura sûrement besoin d'aide pour vérifier que rien n'est cassé.

Actuellement on considère que les collectes vont pas trop changer d'ici le prochain passage dans master pareil pour les sorties don.

**Comment by darnuria** [comment]
Triage: plus ou moins ok je close.

**Comment by WinnieCoe** [comment]
Bonjour, je me permets de poser ça là. Suite à l'installation du système oressource dans une ressourcerie locale, j'ai fait ce petit guide d'installation, il pourra peut-être servir à d'autres. N'hésitez pas à me faire remonter les choses si je me suis raté à la rédaction.

[Tuto Oressource.pdf](https://github.com/mart1ver/oressource/files/9460246/Tuto.Oressource.pdf)

**Comment by darnuria** [comment]
Merci pour la contribution je vais essayer de lire et faire un retour, je suis un peu deborder par mon taff en Rust a gandi, mais c'est toujours tres apprecier je me permet de ping @mart1ver au cas ou il est toujours sur l'affaire. :)

**Comment by darnuria** [comment]
Ah bah euh oups j'ai pas vu passer le temps avec le boulot a temps plein chez Gandi.
